services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ranch_hand
      POSTGRES_PASSWORD: ranch_hand
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
